# Generated by Django 4.0.4 on 2022-05-31 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('data', models.TextField(default='')),
                ('block_hash', models.CharField(max_length=512)),
                ('previous_block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
