# Generated by Django 4.0.4 on 2022-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='block_hash',
        ),
        migrations.AddField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
