# Generated by Django 4.0.4 on 2022-06-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_block_date_alter_block_previous_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='hash',
            field=models.CharField(default=7, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
